### ISSUE TITLE
it would be good if this became a module

### ISSUE THREAD

**Issue by silvesterwali** [BayBreezy/nitro-passport-jwt-example#22]
Hi there. thanks for great example.  since the nuxt auth utils cannot be use as auth api for external purpose like use for flutter or tauri i think this can be a module to hundle those case. here is my origin question on discord https://discord.com/channels/473401852243869706/1310423159459024957

**Comment by BayBreezy** [comment]
Hey @silvesterwali Thanks for checking out this example. 
I think a better approach would be to use [Better Auth](https://www.better-auth.com/).
Give it a try and let me know

**Comment by BayBreezy** [comment]
@silvesterwali I just uploaded an example of using nitro with better auth. You may want to check it out: https://github.com/BayBreezy/nitrojs-better-auth-prisma
